version: '3.8'

services:
  coordinator:
    build: ./coordinator-agent
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - worker-a
      - worker-b
    networks:
      - a2a-network

  worker-a:
    build: ./worker-a
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - a2a-network

  worker-b:
    build: ./worker-b
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge
